### ISSUE TITLE
Branch tune_mob

### ISSUE THREAD

**Issue by mtaktikos** [EterCyber/Chameleon#4]
Have tried out the new branch of the engine, tune_mob2021.
The kns speed is nearly double so high as the main branch, but the evaluation of the main branch is more accurate yet. Have you planned to give the new branch a NNUE weights file? It is mentioned as an UCI option.

**Comment by EterCyber** [comment]
Hello, please note that branch a is only used for testing and is not public. There is no plan to publish the NNUE weight in the future.
